spring.application.name=Rotineiro

# Token JWT (default para dev)
api.security.token.secret=devSecret

# URL do frontend (default para dev)
app.frontend.url=http://localhost:8080

# Configuração do DataSource (dev: H2 em memória)
spring.datasource.url=jdbc:h2:mem:rotineiro
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# Debug JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8095
