
GET http://localhost:8080/v1/routines HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA2ODE4OTksInVzZXJJRCI6MX0.Rgeksl574WcXWWyvQa-01gX2NSf97EGvzFfqyDednhs

###

POST http://localhost:8080/v1/routines HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA2ODE4OTksInVzZXJJRCI6MX0.Rgeksl574WcXWWyvQa-01gX2NSf97EGvzFfqyDednhs
content-type: application/json

{
    "title": "saasd",
    "description": "sss"
}

###

PATCH http://localhost:8080/v1/routines HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA2ODE4OTksInVzZXJJRCI6MX0.Rgeksl574WcXWWyvQa-01gX2NSf97EGvzFfqyDednhs
content-type: application/json

{
    "id": 36,
    "title": "asdas"
}

###

PATCH http://localhost:8080/v1/routines/start/36 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA2ODE4OTksInVzZXJJRCI6MX0.Rgeksl574WcXWWyvQa-01gX2NSf97EGvzFfqyDednhs

###

PATCH http://localhost:8080/v1/routines/complete/36 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA2ODE4OTksInVzZXJJRCI6MX0.Rgeksl574WcXWWyvQa-01gX2NSf97EGvzFfqyDednhs

###

DELETE http://localhost:8080/v1/routines/delete/36 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA2ODE4OTksInVzZXJJRCI6MX0.Rgeksl574WcXWWyvQa-01gX2NSf97EGvzFfqyDednhs
