
GET http://localhost:8080/v1/routines HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA4OTcxMjAsInVzZXJJRCI6MX0.Hn4qW-n32GeJaMfRlis4alqOy2WP5RgDNEjGJpPWNTk

###

POST http://localhost:8080/v1/routines HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA4OTcxMjAsInVzZXJJRCI6MX0.Hn4qW-n32GeJaMfRlis4alqOy2WP5RgDNEjGJpPWNTk
content-type: application/json

{
    "title": "ASDASDASDSDDD",
    "description": "sss"
}

###

PATCH http://localhost:8080/v1/routines HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA4OTcxMjAsInVzZXJJRCI6MX0.Hn4qW-n32GeJaMfRlis4alqOy2WP5RgDNEjGJpPWNTk
content-type: application/json

{
    "id": 36,
    "title": "asdas"
}

###

PATCH http://localhost:8080/v1/routines/start/36 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA4OTcxMjAsInVzZXJJRCI6MX0.Hn4qW-n32GeJaMfRlis4alqOy2WP5RgDNEjGJpPWNTk

###

PATCH http://localhost:8080/v1/routines/complete/36 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA4OTcxMjAsInVzZXJJRCI6MX0.Hn4qW-n32GeJaMfRlis4alqOy2WP5RgDNEjGJpPWNTk

###

DELETE http://localhost:8080/v1/routines/delete/36 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3OTA4OTcxMjAsInVzZXJJRCI6MX0.Hn4qW-n32GeJaMfRlis4alqOy2WP5RgDNEjGJpPWNTk
